#!/bin/bash
# SSL Setup Script for Silvia PID
# This script obtains a Let's Encrypt SSL certificate and configures the service

set -e

DOMAIN="coffee.srjwebster.com"
EMAIL="your-email@example.com"  # UPDATE THIS!

echo "============================================"
echo "Silvia PID SSL Setup"
echo "Domain: $DOMAIN"
echo "============================================"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo "Error: This script must be run as root (use sudo)"
    exit 1
fi

# Check if email is set
if [ "$EMAIL" = "your-email@example.com" ]; then
    echo "Error: Please edit this script and set your email address"
    echo "Edit: $0"
    echo "Change: EMAIL=\"your-email@example.com\""
    exit 1
fi

# Check if domain resolves to this machine
echo "Step 1: Checking DNS resolution..."
DOMAIN_IP=$(dig +short $DOMAIN | tail -n1)
if [ -z "$DOMAIN_IP" ]; then
    echo "Warning: Domain $DOMAIN does not resolve to any IP"
    echo "Make sure your DNS is configured correctly"
    read -p "Continue anyway? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
else
    echo "  Domain resolves to: $DOMAIN_IP"
fi

# Install certbot if not present
echo ""
echo "Step 2: Installing certbot..."
if ! command -v certbot &> /dev/null; then
    apt-get update
    apt-get install -y certbot
    echo "  Certbot installed"
else
    echo "  Certbot already installed"
fi

# Stop services using port 80
echo ""
echo "Step 3: Stopping services on port 80..."
if docker compose -f /opt/silvia-pid/docker-compose.yml ps | grep -q silvia-pid; then
    echo "  Stopping silvia-pid container..."
    docker compose -f /opt/silvia-pid/docker-compose.yml stop silvia-pid
else
    echo "  No running services found"
fi

# Obtain certificate
echo ""
echo "Step 4: Obtaining SSL certificate from Let's Encrypt..."
if [ -d "/etc/letsencrypt/live/$DOMAIN" ]; then
    echo "  Certificate already exists for $DOMAIN"
    read -p "Renew certificate? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        certbot renew --force-renewal
    fi
else
    certbot certonly --standalone \
        -d $DOMAIN \
        --non-interactive \
        --agree-tos \
        -m $EMAIL
fi

echo ""
echo "  Certificate obtained successfully!"
echo "  Location: /etc/letsencrypt/live/$DOMAIN/"

# Create .env file
echo ""
echo "Step 5: Creating .env configuration..."
cat > /opt/silvia-pid/.env << EOF
# Silvia PID Environment Configuration
# Generated by setup-ssl.sh on $(date)

# SSL Configuration
USE_SSL=true
SSL_KEY_PATH=/etc/letsencrypt/live/$DOMAIN/privkey.pem
SSL_CERT_PATH=/etc/letsencrypt/live/$DOMAIN/fullchain.pem

# Port Configuration
HTTP_PORT=80
HTTPS_PORT=443

# MongoDB Configuration
MONGODB_URL=mongodb://mongodb:27017
EOF

echo "  .env file created"

# Set up auto-renewal
echo ""
echo "Step 6: Setting up automatic certificate renewal..."

# Create renewal hook script
cat > /opt/silvia-pid/renew-hook.sh << 'EOF'
#!/bin/bash
# Certificate renewal hook - restart services after renewal
cd /opt/silvia-pid
docker compose restart silvia-pid
EOF

chmod +x /opt/silvia-pid/renew-hook.sh

# Add to crontab if not already present
CRON_JOB="0 */12 * * * certbot renew --quiet --deploy-hook '/opt/silvia-pid/renew-hook.sh' >> /var/log/certbot-renew.log 2>&1"

if ! crontab -l 2>/dev/null | grep -q "certbot renew"; then
    (crontab -l 2>/dev/null; echo "$CRON_JOB") | crontab -
    echo "  Auto-renewal scheduled (checks twice daily)"
else
    echo "  Auto-renewal already configured"
fi

# Test renewal (dry run)
echo ""
echo "Step 7: Testing certificate renewal..."
if certbot renew --dry-run 2>&1 | grep -q "Congratulations"; then
    echo "  Certificate renewal test: PASSED ✓"
else
    echo "  Certificate renewal test: WARNING (may not auto-renew)"
fi

# Restart service with SSL
echo ""
echo "Step 8: Restarting service with SSL enabled..."
cd /opt/silvia-pid
docker compose up -d

# Wait for service to start
echo "  Waiting for service to start..."
sleep 10

# Test HTTPS
echo ""
echo "Step 9: Testing HTTPS connection..."
if curl -f -s -k https://localhost:443 > /dev/null 2>&1; then
    echo "  HTTPS test: PASSED ✓"
else
    echo "  HTTPS test: FAILED (service may still be starting)"
fi

# Summary
echo ""
echo "============================================"
echo "SSL Setup Complete!"
echo "============================================"
echo ""
echo "Your coffee machine is now secured with HTTPS!"
echo ""
echo "Access via:"
echo "  - https://$DOMAIN"
echo "  - https://$DOMAIN/health"
echo ""
echo "Certificates:"
echo "  - Location: /etc/letsencrypt/live/$DOMAIN/"
echo "  - Valid for: 90 days"
echo "  - Auto-renewal: Enabled (checks twice daily)"
echo ""
echo "Next steps:"
echo "  1. Test: https://$DOMAIN"
echo "  2. Update Uptime Kuma monitors to use HTTPS URL"
echo "  3. Set up IFTTT/Google Assistant (see SSL_SETUP.md)"
echo "  4. Consider adding authentication (see SSL_SETUP.md)"
echo ""
echo "Logs:"
echo "  - Service: sudo docker compose -f /opt/silvia-pid/docker-compose.yml logs -f"
echo "  - Certbot renewals: /var/log/certbot-renew.log"
echo ""
echo "Certificate renewal test: sudo certbot renew --dry-run"
echo ""

